version: '3.8'
services: 
  api:
    container_name: api-container
    restart: always
    build: ./backend
    ports: 
      - "8081:8081"
    depends_on: 
      - db
  client:
    container_name: client-container
    restart: always
    build: ./frontend
    ports: 
      - "8080:8080"
    depends_on: 
      - api
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edtech_enrollment
#      MYSQL_USER: root_user
#      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - 'apiDB/db/data:/var/lib/mysql'
      - 'apiDB/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - 'apiDB/db/sql:/docker-entrypoint-initdb.d'

volumes: 
  apiDB: