version: '3.8'
services:
  api:
    container_name: api-edtech
    restart: always
    build: ./api-edtech
    environment:
      - PORT=8081
      - DATABASE_URL=mysql://root:root@db:3306/edtech_enrollment?charset=utf8
    ports:
      - "8081:8081"
    depends_on:
      - db
    command: bash -c " npx prisma migrate dev && npm run dev"
    volumes:
      - ./api-edtech:/api-edtech
  client:
    container_name: vuejs
    restart: always
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
    volumes:
      - ./frontend:/client
  db-test:
    container_name: mysql8_test
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edtech_enrollment
      # MYSQL_USER: root_user
      # MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3303:3306'
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edtech_enrollment
      #      MYSQL_USER: root_user
      #      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
